config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Hauptsite
  root 'posts#index'
  #Example of regular route:
  # get 'products/:id' => 'catalog#view'
  #coustom  weg
  get 'about' => 'pages#about'

  #Example resource routes
  #resources :products
  resources :posts


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @title = 'About us'
    @content = 'Ein kleines Projekt, welches immer weiter geführt werden soll. Es soll als erkplattform fr mich anfangen und verschieden Datenbanken enthalten, um mein Leben zu organiesieren und weiter entwickeln.'
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_id, only: [:show,:update,:destroy,:edit]

  def index
    @Posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    #render plain: params[:post].inspect

    #sicherheit das nur itle und Inhalt übertragen werden können
    # ich habe ja ne private methode gschrien´ben für den anhängsel
    # @post = Post.create(params.require(:post).permit(:title,:body))
    @post = Post.create(post_params)

    if @post.save
      redirect_to  root_path
    else
      render :new
    end
  end

##    @post = Post.new(post_params)
##    @post.save
##    redirect_to @post

    def edit
    end

    def update
      if @post.update(post_params)
        redirect_to root_path
      else
        render :edit
      end
    end

    def destroy
      @post.destroy
      redirect_to root_path
    end



##  private
  def post_params
    params.require(:post).permit(:title, :body)
  end

  def find_id
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7 text-center">
      <div class="about_page">

        <h3><%= @title %></h3>
        <p><%= @content %></p>
      </div>

    </div>

  </div>



</div>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |f| %>
<%# form_with scope: :post, url: posts_path, local: true do |f| %>
<%# form_for :post, url: posts_path do |f|  alernative alt%>
  <p>
    <%= f.text_field :title,class: 'form-control',placeholder: 'Title' %> <br>
    <%= f.text_area :body,class: 'form-control',placeholder: 'Content' %>
  </p>

  <p>
    <%# Blogscntroller new,create erstellen %>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<div class="container",id=form_container>


  <h1>Edit Post</h1>
  <hr>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">

    <%@Posts.each do |post| %>
      <div class="col-md-4" id='card_margin'>
        <div class="card" style='width 18rem'>
          <div class="card-body">
            <h5 class="card-title"><%= post.title %></h5>
            <p class="card-text"><%= post.body %></p>
            <%= link_to 'View', post_path(post), class: 'btn btn-outline-primary' %>
            <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-outline-primary' %>
            <%= link_to 'Delete', post_path(post),class: 'btn btn-outline-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
          </div>

        </div>
      </div>
    <% end %>

    </div>
</div>

app/views/posts/new.html.erb
<div class="container",id="form_container">
  <h3>Add Post</h3>
  <hr>  <br>

  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="container", id="show_pages">


  <h2><%= @post.title%></h2>
  <hr>
  <br>
  <p><%= @post.body %></p>

  <%= link_to "Back", root_path, class:'btn btn-outline-primary',id:"show_button" %>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#"> &#x2083;202 <sub>tiga</sub>HOGEI <sub>hiru</sub>duapuluh &#x16D0&#x16DA&#x16D0&#x16DA</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-md-auto">
      <li class="nav-item">
        <%= link_to 'About', about_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Blog', posts_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to "New Blog Post", new_post_path, class: 'nav-link ' %>
      </li>

    </ul>
  </div>
</nav>